// Import canonical addresses and config as single source of truth
import {
  CANONICAL_ADDRESSES,
  CHAIN_ID,
  RPC_URL as CANONICAL_RPC_URL,
  DEPLOY_BLOCK as CANONICAL_DEPLOY_BLOCK,
} from "@/config/canonical";

const DEFAULT_CONTRACTS = {
  PRAYER_REGISTRY: "0x6FC7301fad7Ca0294152b23FD4f0467200376d65",
  PRAYER_MIRROR: "0x8ff39c2a78FaF7d655e4Dab03076Cb26C97007FF",
  LOREBOARD_BOARD: CANONICAL_ADDRESSES.board,
  LOREBOARD_TREASURY: CANONICAL_ADDRESSES.treasury,
  LOREBOARD_VOTING: CANONICAL_ADDRESSES.voting,
  LOREBOARD_MANIFEST_STORE: CANONICAL_ADDRESSES.manifestStore,
  LOREBOARD_LIVE_NFT: CANONICAL_ADDRESSES.liveNFT,
  VOTING_POWER: CANONICAL_ADDRESSES.votingPowerSource,
} as const;

export const CONTRACTS = {
  // ── Existing (prayer + legacy loreboard) ──
  PRAYER_REGISTRY: process.env.NEXT_PUBLIC_PRAYER_REGISTRY ?? DEFAULT_CONTRACTS.PRAYER_REGISTRY,
  PRAYER_MIRROR: process.env.NEXT_PUBLIC_PRAYER_MIRROR ?? DEFAULT_CONTRACTS.PRAYER_MIRROR,
  LOREBOARD_BOARD: process.env.NEXT_PUBLIC_LOREBOARD_BOARD ?? DEFAULT_CONTRACTS.LOREBOARD_BOARD,
  LOREBOARD_TREASURY: process.env.NEXT_PUBLIC_LOREBOARD_TREASURY ?? DEFAULT_CONTRACTS.LOREBOARD_TREASURY,
  LOREBOARD_VOTING: process.env.NEXT_PUBLIC_LOREBOARD_VOTING ?? DEFAULT_CONTRACTS.LOREBOARD_VOTING,
  LOREBOARD_MANIFEST_STORE:
    process.env.NEXT_PUBLIC_LOREBOARD_MANIFEST_STORE ?? DEFAULT_CONTRACTS.LOREBOARD_MANIFEST_STORE,
  LOREBOARD_LIVE_NFT:
    process.env.NEXT_PUBLIC_LOREBOARD_LIVE_NFT ?? DEFAULT_CONTRACTS.LOREBOARD_LIVE_NFT,
  VOTING_POWER: process.env.NEXT_PUBLIC_VOTING_POWER ?? DEFAULT_CONTRACTS.VOTING_POWER,

  // ── FOID v1: Swipe + Gallery ──
  FOID_TREST: process.env.NEXT_PUBLIC_FOID_TREST ?? CANONICAL_ADDRESSES.foidTrest,
  STREAK_VOTING_POWER: process.env.NEXT_PUBLIC_STREAK_VOTING_POWER ?? CANONICAL_ADDRESSES.streakVotingPower,
  PRAYER_TIERS: process.env.NEXT_PUBLIC_PRAYER_TIERS ?? CANONICAL_ADDRESSES.prayerTiers,
  SWIPE: process.env.NEXT_PUBLIC_SWIPE ?? CANONICAL_ADDRESSES.swipe,
  SWIPE_LOREBOARD: process.env.NEXT_PUBLIC_SWIPE_LOREBOARD ?? CANONICAL_ADDRESSES.swipeLoreboard,

  // ── Legacy v1 (deprecated — kept for build compatibility) ──
  FOID_TREST_GOVERNANCE: "",

  // ── Fee config (readable from env) ──
  PLACEMENT_FEE_WEI: process.env.NEXT_PUBLIC_PLACEMENT_FEE_WEI ?? "1000000000000000", // 0.001 ETH default
  SWIPE_SUBMISSION_FEE: process.env.NEXT_PUBLIC_SWIPE_SUBMISSION_FEE ?? "1000000000000000", // 0.001 ETH
  DUEL_SUBMISSION_FEE: process.env.NEXT_PUBLIC_DUEL_SUBMISSION_FEE ?? "1000000000000000", // 0.001 ETH (legacy)
  MIFOID_MINT_FEE: process.env.NEXT_PUBLIC_MIFOID_MINT_FEE ?? "10000000000000000", // 0.01 ETH (legacy)
  FLAG_FEE_WEI: process.env.NEXT_PUBLIC_FLAG_FEE_WEI ?? "1000000000000000", // 0.001 ETH
} as const;

export const CHAIN_CONFIG = {
  id: CHAIN_ID,
  name: process.env.NEXT_PUBLIC_CHAIN_NAME ?? "Fluent",
  rpcUrl: CANONICAL_RPC_URL,
  blockExplorer: process.env.NEXT_PUBLIC_BLOCK_EXPLORER ?? "https://testnet.fluentscan.xyz",
} as const;

export const RPC_URL = process.env.NEXT_PUBLIC_RPC_URL ?? CHAIN_CONFIG.rpcUrl;

// Use canonical deploy block
export const DEPLOY_BLOCK: bigint = CANONICAL_DEPLOY_BLOCK;
