// Import canonical addresses and config as single source of truth
import {
  CANONICAL_ADDRESSES,
  CHAIN_ID,
  RPC_URL as CANONICAL_RPC_URL,
  DEPLOY_BLOCK as CANONICAL_DEPLOY_BLOCK,
} from "@/config/canonical";

const DEFAULT_CONTRACTS = {
  PRAYER_REGISTRY: "0x6FC7301fad7Ca0294152b23FD4f0467200376d65",
  PRAYER_MIRROR: "0x8ff39c2a78FaF7d655e4Dab03076Cb26C97007FF",
  LOREBOARD_BOARD: CANONICAL_ADDRESSES.board,
  LOREBOARD_TREASURY: CANONICAL_ADDRESSES.treasury,
  LOREBOARD_VOTING: CANONICAL_ADDRESSES.voting,
  LOREBOARD_MANIFEST_STORE: CANONICAL_ADDRESSES.manifestStore,
  VOTING_POWER: CANONICAL_ADDRESSES.votingPowerSource,
} as const;

export const CONTRACTS = {
  PRAYER_REGISTRY: process.env.NEXT_PUBLIC_PRAYER_REGISTRY ?? DEFAULT_CONTRACTS.PRAYER_REGISTRY,
  PRAYER_MIRROR: process.env.NEXT_PUBLIC_PRAYER_MIRROR ?? DEFAULT_CONTRACTS.PRAYER_MIRROR,
  LOREBOARD_BOARD: process.env.NEXT_PUBLIC_LOREBOARD_BOARD ?? DEFAULT_CONTRACTS.LOREBOARD_BOARD,
  LOREBOARD_TREASURY: process.env.NEXT_PUBLIC_LOREBOARD_TREASURY ?? DEFAULT_CONTRACTS.LOREBOARD_TREASURY,
  LOREBOARD_VOTING: process.env.NEXT_PUBLIC_LOREBOARD_VOTING ?? DEFAULT_CONTRACTS.LOREBOARD_VOTING,
  LOREBOARD_MANIFEST_STORE:
    process.env.NEXT_PUBLIC_LOREBOARD_MANIFEST_STORE ?? DEFAULT_CONTRACTS.LOREBOARD_MANIFEST_STORE,
  VOTING_POWER: process.env.NEXT_PUBLIC_VOTING_POWER ?? DEFAULT_CONTRACTS.VOTING_POWER,
} as const;

export const CHAIN_CONFIG = {
  id: CHAIN_ID, // Use canonical chain ID
  name: "Fluent Testnet",
  rpcUrl: CANONICAL_RPC_URL,
  blockExplorer: "https://testnet.fluentscan.xyz",
} as const;

export const RPC_URL = process.env.NEXT_PUBLIC_RPC_URL ?? CHAIN_CONFIG.rpcUrl;

// Use canonical deploy block
export const DEPLOY_BLOCK: bigint = CANONICAL_DEPLOY_BLOCK;
