export const DUEL_ARENA_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_foidTrest", type: "address" },
      { name: "_votingPowerSource", type: "address" },
      { name: "_operator", type: "address" },
      { name: "_votingWindowSeconds", type: "uint32" },
      { name: "_submissionFee", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "duelCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "duels",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "submissionA", type: "uint256" },
      { name: "submissionB", type: "uint256" },
      { name: "votingStartsAt", type: "uint64" },
      { name: "votingEndsAt", type: "uint64" },
      { name: "winner", type: "uint8" },
      { name: "totalVotesA", type: "uint256" },
      { name: "totalVotesB", type: "uint256" },
      { name: "trestEntryId", type: "uint256" },
      { name: "finalized", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "finalizeDuel",
    inputs: [{ name: "duelId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "foidTrest",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDuel",
    inputs: [{ name: "duelId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "submissionA", type: "uint256" },
          { name: "submissionB", type: "uint256" },
          { name: "votingStartsAt", type: "uint64" },
          { name: "votingEndsAt", type: "uint64" },
          { name: "winner", type: "uint8" },
          { name: "totalVotesA", type: "uint256" },
          { name: "totalVotesB", type: "uint256" },
          { name: "trestEntryId", type: "uint256" },
          { name: "finalized", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSubmission",
    inputs: [{ name: "subId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "creator", type: "address" },
          { name: "ipfsCid", type: "string" },
          { name: "submittedAt", type: "uint64" },
          { name: "matched", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasVotedOnDuel",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "matchDuel",
    inputs: [
      { name: "subA", type: "uint256" },
      { name: "subB", type: "uint256" },
    ],
    outputs: [{ name: "duelId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mifoidNFT",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "operator",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingSubmissions",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setMifoidNFT",
    inputs: [{ name: "_mifoidNFT", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOperator",
    inputs: [{ name: "newOp", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOwner",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSubmissionFee",
    inputs: [{ name: "newFee", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setVotingWindowSeconds",
    inputs: [{ name: "newWindow", type: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submit",
    inputs: [{ name: "ipfsCid", type: "string" }],
    outputs: [{ name: "submissionId", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "submissionCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "submissionFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "submissions",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "creator", type: "address" },
      { name: "ipfsCid", type: "string" },
      { name: "submittedAt", type: "uint64" },
      { name: "matched", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "unmatchedCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vote",
    inputs: [
      { name: "duelId", type: "uint256" },
      { name: "side", type: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "votingPowerSource",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "votingWindowSeconds",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "DuelCreated",
    anonymous: false,
    inputs: [
      { name: "duelId", type: "uint256", indexed: true },
      { name: "submissionA", type: "uint256", indexed: false },
      { name: "submissionB", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DuelFinalized",
    anonymous: false,
    inputs: [
      { name: "duelId", type: "uint256", indexed: true },
      { name: "winner", type: "uint8", indexed: false },
      { name: "trestEntryId", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DuelVoteCast",
    anonymous: false,
    inputs: [
      { name: "duelId", type: "uint256", indexed: true },
      { name: "voter", type: "address", indexed: true },
      { name: "side", type: "uint8", indexed: false },
      { name: "weight", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OperatorChanged",
    anonymous: false,
    inputs: [
      { name: "oldOp", type: "address", indexed: true },
      { name: "newOp", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "OwnerChanged",
    anonymous: false,
    inputs: [
      { name: "oldOwner", type: "address", indexed: true },
      { name: "newOwner", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "Submitted",
    anonymous: false,
    inputs: [
      { name: "submissionId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "ipfsCid", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "VotingWindowChanged",
    anonymous: false,
    inputs: [
      { name: "oldWindow", type: "uint32", indexed: false },
      { name: "newWindow", type: "uint32", indexed: false },
    ],
  },
] as const;
