export const FOID_TREST_ABI = [
  {
    type: "constructor",
    inputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addEntry",
    inputs: [
      { name: "creator", type: "address" },
      { name: "ipfsCid", type: "string" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "path", type: "uint8" },
      { name: "duelId", type: "uint256" },
    ],
    outputs: [{ name: "entryId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "authorizeEntryPoint",
    inputs: [{ name: "entryPoint", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "authorizedEntryPoints",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "entries",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "creator", type: "address" },
      { name: "ipfsCid", type: "string" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
      { name: "placedAt", type: "uint64" },
      { name: "path", type: "uint8" },
      { name: "duelId", type: "uint256" },
      { name: "visible", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "entryCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEntry",
    inputs: [{ name: "entryId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "creator", type: "address" },
          { name: "ipfsCid", type: "string" },
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "placedAt", type: "uint64" },
          { name: "path", type: "uint8" },
          { name: "duelId", type: "uint256" },
          { name: "visible", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "revokeEntryPoint",
    inputs: [{ name: "entryPoint", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMetadata",
    inputs: [
      { name: "entryId", type: "uint256" },
      { name: "title", type: "string" },
      { name: "description", type: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOwner",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setVisibility",
    inputs: [
      { name: "entryId", type: "uint256" },
      { name: "visible", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "EntryPlaced",
    anonymous: false,
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "path", type: "uint8", indexed: false },
      { name: "ipfsCid", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "EntryPointAuthorized",
    anonymous: false,
    inputs: [{ name: "entryPoint", type: "address", indexed: true }],
  },
  {
    type: "event",
    name: "EntryPointRevoked",
    anonymous: false,
    inputs: [{ name: "entryPoint", type: "address", indexed: true }],
  },
  {
    type: "event",
    name: "MetadataUpdated",
    anonymous: false,
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "title", type: "string", indexed: false },
      { name: "description", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OwnerChanged",
    anonymous: false,
    inputs: [
      { name: "oldOwner", type: "address", indexed: true },
      { name: "newOwner", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "VisibilityChanged",
    anonymous: false,
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "visible", type: "bool", indexed: false },
    ],
  },
] as const;
