export const FOID_TREST_GOVERNANCE_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_foidTrest", type: "address" },
      { name: "_votingPowerSource", type: "address" },
      { name: "_feeRecipient", type: "address" },
      { name: "_flagFeeWei", type: "uint256" },
      { name: "_flagThreshold", type: "uint8" },
      { name: "_removalVoteWindowSeconds", type: "uint32" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "flagPost",
    inputs: [{ name: "entryId", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "voteOnRemoval",
    inputs: [
      { name: "voteId", type: "uint256" },
      { name: "support", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveRemovalVote",
    inputs: [{ name: "voteId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getFlagCount",
    inputs: [{ name: "entryId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getVote",
    inputs: [{ name: "voteId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "entryId", type: "uint256" },
          { name: "startsAt", type: "uint64" },
          { name: "endsAt", type: "uint64" },
          { name: "votesFor", type: "uint256" },
          { name: "votesAgainst", type: "uint256" },
          { name: "resolved", type: "bool" },
          { name: "removalPassed", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "flagFeeWei",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "flagThreshold",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "removalVoteWindowSeconds",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "voteCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "activeVoteForEntry",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasFlagged",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasVotedOnRemoval",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeRecipient",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PostFlagged",
    anonymous: false,
    inputs: [
      { name: "entryId", type: "uint256", indexed: true },
      { name: "flagger", type: "address", indexed: true },
      { name: "flagCount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RemovalVoteStarted",
    anonymous: false,
    inputs: [
      { name: "entryId", type: "uint256", indexed: true },
      { name: "voteId", type: "uint256", indexed: true },
    ],
  },
  {
    type: "event",
    name: "RemovalVoteCast",
    anonymous: false,
    inputs: [
      { name: "voteId", type: "uint256", indexed: true },
      { name: "voter", type: "address", indexed: true },
      { name: "support", type: "bool", indexed: false },
      { name: "weight", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RemovalVoteResolved",
    anonymous: false,
    inputs: [
      { name: "voteId", type: "uint256", indexed: true },
      { name: "entryId", type: "uint256", indexed: true },
      { name: "removed", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OwnerChanged",
    anonymous: false,
    inputs: [
      { name: "oldOwner", type: "address", indexed: true },
      { name: "newOwner", type: "address", indexed: true },
    ],
  },
] as const;
