export const SWIPE_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_gallery", type: "address" },
      { name: "_votingPowerSource", type: "address" },
      { name: "_operator", type: "address" },
      { name: "_feeRecipient", type: "address" },
      { name: "_submissionFee", type: "uint256" },
      { name: "_votingWindowSeconds", type: "uint32" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "VOTE_TYPEHASH",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "eip712Domain",
    inputs: [],
    outputs: [
      { name: "fields", type: "bytes1" },
      { name: "name", type: "string" },
      { name: "version", type: "string" },
      { name: "chainId", type: "uint256" },
      { name: "verifyingContract", type: "address" },
      { name: "salt", type: "bytes32" },
      { name: "extensions", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeRecipient",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "finalize",
    inputs: [
      { name: "proposalId", type: "uint256" },
      { name: "voters", type: "address[]" },
      { name: "approvals", type: "bool[]" },
      { name: "deadlines", type: "uint256[]" },
      { name: "signatures", type: "bytes[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "gallery",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getProposal",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "proposer", type: "address" },
          { name: "ipfsCid", type: "string" },
          { name: "createdAt", type: "uint64" },
          { name: "votingEndsAt", type: "uint64" },
          { name: "finalized", type: "bool" },
          { name: "canonized", type: "bool" },
          { name: "trestEntryId", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "operator",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proposalCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "propose",
    inputs: [{ name: "ipfsCid", type: "string" }],
    outputs: [{ name: "proposalId", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "setFeeRecipient",
    inputs: [{ name: "newRecipient", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOperator",
    inputs: [{ name: "newOp", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOwner",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSubmissionFee",
    inputs: [{ name: "newFee", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setVotingWindowSeconds",
    inputs: [{ name: "newWindow", type: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submissionFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "votingPowerSource",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "votingWindowSeconds",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Canonized",
    inputs: [
      { name: "proposalId", type: "uint256", indexed: true },
      { name: "trestEntryId", type: "uint256", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EIP712DomainChanged",
    inputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeeRecipientChanged",
    inputs: [
      { name: "oldRecipient", type: "address", indexed: true },
      { name: "newRecipient", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Finalized",
    inputs: [
      { name: "proposalId", type: "uint256", indexed: true },
      { name: "canonized", type: "bool", indexed: false },
      { name: "weightFor", type: "uint256", indexed: false },
      { name: "weightAgainst", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OperatorChanged",
    inputs: [
      { name: "oldOp", type: "address", indexed: true },
      { name: "newOp", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnerChanged",
    inputs: [
      { name: "oldOwner", type: "address", indexed: true },
      { name: "newOwner", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Proposed",
    inputs: [
      { name: "proposalId", type: "uint256", indexed: true },
      { name: "proposer", type: "address", indexed: true },
      { name: "ipfsCid", type: "string", indexed: false },
      { name: "votingEndsAt", type: "uint64", indexed: false },
    ],
    anonymous: false,
  },
] as const;
