export const SWIPE_LOREBOARD_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_feeRecipient", type: "address" },
      { name: "_votingPowerSource", type: "address" },
      { name: "_placementFeeWei", type: "uint256" },
      { name: "_flagFeeWei", type: "uint256" },
      { name: "_flagThreshold", type: "uint8" },
      { name: "_removalVoteWindowSeconds", type: "uint32" },
      { name: "_operator", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "MAX_CELLS",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TILE",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "activeVoteForPlacement",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeRecipient",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "flagFeeWei",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "flagPlacement",
    inputs: [{ name: "placementId", type: "uint256" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "flagThreshold",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getFlagCount",
    inputs: [{ name: "placementId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPlacement",
    inputs: [{ name: "placementId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "placer", type: "address" },
          { name: "x", type: "int32" },
          { name: "y", type: "int32" },
          { name: "w", type: "uint32" },
          { name: "h", type: "uint32" },
          { name: "cells", type: "uint32" },
          { name: "cidBytes", type: "bytes" },
          { name: "placedAt", type: "uint64" },
          { name: "removed", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRemovalVote",
    inputs: [{ name: "voteId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "placementId", type: "uint256" },
          { name: "startsAt", type: "uint64" },
          { name: "endsAt", type: "uint64" },
          { name: "votesFor", type: "uint256" },
          { name: "votesAgainst", type: "uint256" },
          { name: "resolved", type: "bool" },
          { name: "removalPassed", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasFlagged",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasVotedOnRemoval",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "place",
    inputs: [
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
      { name: "w", type: "uint32" },
      { name: "h", type: "uint32" },
      { name: "cidBytes", type: "bytes" },
    ],
    outputs: [{ name: "placementId", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "placeFor",
    inputs: [
      { name: "placer", type: "address" },
      { name: "x", type: "int32" },
      { name: "y", type: "int32" },
      { name: "w", type: "uint32" },
      { name: "h", type: "uint32" },
      { name: "cidBytes", type: "bytes" },
    ],
    outputs: [{ name: "placementId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "operator",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setOperator",
    inputs: [{ name: "newOperator", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "placementCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "placementFeeWei",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "removalVoteWindowSeconds",
    inputs: [],
    outputs: [{ name: "", type: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resolveRemovalVote",
    inputs: [{ name: "voteId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFeeRecipient",
    inputs: [{ name: "newRecipient", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFlagFee",
    inputs: [{ name: "newFee", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFlagThreshold",
    inputs: [{ name: "newThreshold", type: "uint8" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOwner",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPlacementFee",
    inputs: [{ name: "newFee", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setRemovalVoteWindow",
    inputs: [{ name: "newWindow", type: "uint32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setVotingPowerSource",
    inputs: [{ name: "newSource", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "voteCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "voteOnRemoval",
    inputs: [
      { name: "voteId", type: "uint256" },
      { name: "support", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "votingPowerSource",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "FeeRecipientChanged",
    inputs: [
      { name: "oldRecipient", type: "address", indexed: true },
      { name: "newRecipient", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnerChanged",
    inputs: [
      { name: "oldOwner", type: "address", indexed: true },
      { name: "newOwner", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlacementCreated",
    inputs: [
      { name: "placementId", type: "uint256", indexed: true },
      { name: "placer", type: "address", indexed: true },
      { name: "x", type: "int32", indexed: false },
      { name: "y", type: "int32", indexed: false },
      { name: "w", type: "uint32", indexed: false },
      { name: "h", type: "uint32", indexed: false },
      { name: "cells", type: "uint32", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlacementFlagged",
    inputs: [
      { name: "placementId", type: "uint256", indexed: true },
      { name: "flagger", type: "address", indexed: true },
      { name: "flagCount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PlacementRemoved",
    inputs: [{ name: "placementId", type: "uint256", indexed: true }],
    anonymous: false,
  },
  {
    type: "event",
    name: "RemovalVoteCast",
    inputs: [
      { name: "voteId", type: "uint256", indexed: true },
      { name: "voter", type: "address", indexed: true },
      { name: "support", type: "bool", indexed: false },
      { name: "weight", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RemovalVoteResolved",
    inputs: [
      { name: "voteId", type: "uint256", indexed: true },
      { name: "placementId", type: "uint256", indexed: true },
      { name: "removed", type: "bool", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RemovalVoteStarted",
    inputs: [
      { name: "placementId", type: "uint256", indexed: true },
      { name: "voteId", type: "uint256", indexed: true },
    ],
    anonymous: false,
  },
] as const;
