// scripts/caption-placements.ts
// Writes src/content/placementCaptions.json: a title, alt text, a short
// description, search tags and a sensitive-content flag for every Loreboard
// placement image, written by Claude from the image itself. The site uses
// them for image alt text, the /board/proposal/<id> pages, the placements
// gallery and the image sitemap.
//
// Keyed by IPFS CID. CIDs are content-addressed, so a caption can never go
// stale; the script only captions CIDs it has not seen, unless --force.
// The output is one JSON file: review it in the PR diff before it ships.
//
//   pnpm exec tsx scripts/caption-placements.ts             # new placements only
//   pnpm exec tsx scripts/caption-placements.ts --limit 3   # try a few first
//   pnpm exec tsx scripts/caption-placements.ts --dry-run   # print, don't write
//   pnpm exec tsx scripts/caption-placements.ts --force     # redo everything
//
// Needs ANTHROPIC_API_KEY (the environment, else .env.local). Reads the live
// placement list and edge-cached image tiles from FOID_SITE_URL
// (default https://foid.fun).

import fs from "node:fs";
import path from "node:path";
import Anthropic from "@anthropic-ai/sdk";
import { jsonSchemaOutputFormat } from "@anthropic-ai/sdk/helpers/json-schema";

const SITE = (process.env.FOID_SITE_URL ?? "https://foid.fun").replace(/\/+$/, "");
const OUT_FILE = path.join(process.cwd(), "src/content/placementCaptions.json");
const MODEL = "claude-opus-5";
const CONCURRENCY = 3;
// Input/output USD per million tokens for MODEL, for the cost estimate only.
const PRICE = { input: 5, output: 25 };

const args = process.argv.slice(2);
const FORCE = args.includes("--force");
const DRY_RUN = args.includes("--dry-run");
const limitIndex = args.indexOf("--limit");
const LIMIT = limitIndex >= 0 ? Number(args[limitIndex + 1]) : Infinity;

export type PlacementCaption = {
  title: string;
  alt: string;
  description: string;
  tags: string[];
  sensitive: boolean;
  model: string;
  captionedAt: string;
};

type CaptionFile = {
  note: string;
  captions: Record<string, PlacementCaption>;
};

const CAPTION_SCHEMA = {
  type: "object",
  properties: {
    title: { type: "string", description: "3 to 8 words naming the image, like a gallery label." },
    alt: { type: "string", description: "One sentence of alt text, at most 125 characters." },
    description: { type: "string", description: "One or two sentences, at most 280 characters." },
    tags: { type: "array", items: { type: "string" }, description: "3 to 6 lowercase search keywords." },
    sensitive: { type: "boolean", description: "True for nudity, sexual content, graphic violence, hate symbols or slurs." },
  },
  required: ["title", "alt", "description", "tags", "sensitive"],
  additionalProperties: false,
} as const;

const SYSTEM = `You write captions for images on the FOID Loreboard, a community-voted collage of memes and internet art at foid.fun. Each caption becomes the image's alt text and the title and description of its public page, so it has to be accurate for someone who can't see the image and useful to someone searching for it.

Describe what is actually in the image: the main subject, any readable text (quote short text exactly), the format or style (photo, drawing, 3D render, screenshot, pixel art, collage), and the joke or reference when the image itself makes it clear. Stay neutral and literal. Don't name real people unless their name is written in the image, and don't invent backstory.

- title: 3 to 8 words naming the image, like a gallery label. No quotes, no trailing period.
- alt: one sentence, at most 125 characters, starting with the subject. Never start with "Image of" or "Picture of".
- description: one or two sentences, at most 280 characters, adding what the alt text leaves out.
- tags: 3 to 6 lowercase keywords someone might search for.
- sensitive: true if the image shows nudity, sexual content, graphic violence, hate symbols or slurs, otherwise false. When true, keep every field clinical and brief.`;

function loadApiKey(): string {
  if (process.env.ANTHROPIC_API_KEY) return process.env.ANTHROPIC_API_KEY;
  const envFile = path.join(process.cwd(), ".env.local");
  if (fs.existsSync(envFile)) {
    for (const line of fs.readFileSync(envFile, "utf8").split("\n")) {
      const match = line.match(/^\s*ANTHROPIC_API_KEY\s*=\s*"?([^"\s]+)"?\s*$/);
      if (match) return match[1];
    }
  }
  throw new Error("ANTHROPIC_API_KEY is not set (environment or .env.local)");
}

function readCaptions(): CaptionFile {
  if (!fs.existsSync(OUT_FILE)) {
    return {
      note: "Generated by scripts/caption-placements.ts from each image. Keyed by IPFS CID. Edit freely; the script never overwrites an existing entry without --force.",
      captions: {},
    };
  }
  return JSON.parse(fs.readFileSync(OUT_FILE, "utf8")) as CaptionFile;
}

function writeCaptions(file: CaptionFile): void {
  // Stable key order keeps diffs reviewable.
  const sorted = Object.fromEntries(Object.entries(file.captions).sort(([a], [b]) => a.localeCompare(b)));
  fs.writeFileSync(OUT_FILE, `${JSON.stringify({ ...file, captions: sorted }, null, 2)}\n`);
}

type Placement = { id: string; proposalId: number | string; cid: string };

async function fetchPlacements(): Promise<Placement[]> {
  const res = await fetch(`${SITE}/api/proposals`);
  if (!res.ok) throw new Error(`/api/proposals returned ${res.status}`);
  const body = (await res.json()) as { proposals?: Placement[] };
  return (body.proposals ?? []).filter((p) => typeof p.cid === "string" && p.cid.length > 0);
}

const MEDIA_TYPES = new Set(["image/jpeg", "image/png", "image/gif", "image/webp"]);

async function fetchImage(cid: string): Promise<{ data: string; mediaType: "image/jpeg" | "image/png" | "image/gif" | "image/webp" }> {
  // 512 CSS px at the proxy's 2x = about 1024 px wide: plenty for a caption,
  // small enough to keep image tokens low. Served from the Cloudflare edge.
  const res = await fetch(`${SITE}/img/ipfs/${cid}.webp?w=512&f=webp&q=85`);
  if (!res.ok) throw new Error(`image ${res.status}`);
  const mediaType = (res.headers.get("content-type") ?? "").split(";")[0].trim();
  if (!MEDIA_TYPES.has(mediaType)) throw new Error(`unsupported image type ${mediaType || "unknown"}`);
  const bytes = Buffer.from(await res.arrayBuffer());
  return { data: bytes.toString("base64"), mediaType: mediaType as "image/jpeg" | "image/png" | "image/gif" | "image/webp" };
}

function clean(caption: Omit<PlacementCaption, "model" | "captionedAt">): Omit<PlacementCaption, "model" | "captionedAt"> {
  const trim = (value: string, max: number) => {
    const text = value.replace(/\s+/g, " ").trim();
    if (text.length <= max) return text;
    const cut = text.slice(0, max - 1);
    return `${cut.slice(0, cut.lastIndexOf(" "))}…`;
  };
  return {
    title: trim(caption.title.replace(/^["']|["']$/g, "").replace(/\.$/, ""), 70),
    alt: trim(caption.alt, 140),
    description: trim(caption.description, 300),
    tags: [...new Set(caption.tags.map((t) => t.toLowerCase().trim()).filter(Boolean))].slice(0, 6),
    sensitive: caption.sensitive,
  };
}

async function main() {
  const client = new Anthropic({ apiKey: loadApiKey() });
  const file = readCaptions();
  const placements = await fetchPlacements();
  const byCid = new Map<string, Placement>();
  for (const p of placements) if (!byCid.has(p.cid)) byCid.set(p.cid, p);
  const todo = [...byCid.values()].filter((p) => FORCE || !file.captions[p.cid]).slice(0, LIMIT);
  console.log(`${byCid.size} placements, ${Object.keys(file.captions).length} already captioned, ${todo.length} to do`);

  let inputTokens = 0;
  let outputTokens = 0;
  const failures: string[] = [];
  let next = 0;

  async function worker() {
    while (next < todo.length) {
      const placement = todo[next++];
      const label = `#${placement.proposalId} ${placement.cid.slice(0, 12)}`;
      try {
        const image = await fetchImage(placement.cid);
        // Server-side fallbacks re-run a declined request on the model
        // Anthropic recommends for that refusal category. The installed SDK
        // predates the field, hence the cast.
        const params = {
          model: MODEL,
          max_tokens: 16000,
          betas: ["server-side-fallback-2026-07-01"],
          fallbacks: "default",
          system: SYSTEM,
          output_config: { effort: "low", format: jsonSchemaOutputFormat(CAPTION_SCHEMA) },
          messages: [
            {
              role: "user",
              content: [
                { type: "image", source: { type: "base64", media_type: image.mediaType, data: image.data } },
                { type: "text", text: `Placement #${placement.proposalId} on the Loreboard.` },
              ],
            },
          ],
        };
        const response = await client.beta.messages.parse(params as unknown as Parameters<typeof client.beta.messages.parse>[0]);
        inputTokens += response.usage.input_tokens;
        outputTokens += response.usage.output_tokens;
        if (response.stop_reason === "refusal") {
          // stop_details is GA but newer than the installed SDK's types.
          const details = (response as { stop_details?: { category?: string | null } | null }).stop_details;
          failures.push(`${label}: declined (${details?.category ?? "no category"})`);
          continue;
        }
        const parsed = response.parsed_output as Omit<PlacementCaption, "model" | "captionedAt"> | null;
        if (!parsed) {
          failures.push(`${label}: no parsable output (stop_reason ${response.stop_reason})`);
          continue;
        }
        const caption: PlacementCaption = { ...clean(parsed), model: response.model, captionedAt: new Date().toISOString().slice(0, 10) };
        console.log(`${label}  ${caption.sensitive ? "[sensitive] " : ""}${caption.title}  |  ${caption.alt}`);
        if (!DRY_RUN) {
          file.captions[placement.cid] = caption;
          writeCaptions(file); // after every image, so an interrupted run keeps its work
        }
      } catch (error) {
        if (error instanceof Anthropic.RateLimitError) {
          failures.push(`${label}: rate limited, rerun later`);
        } else if (error instanceof Anthropic.APIError) {
          failures.push(`${label}: API ${error.status} ${error.message.slice(0, 120)}`);
        } else {
          failures.push(`${label}: ${error instanceof Error ? error.message : String(error)}`);
        }
      }
    }
  }

  await Promise.all(Array.from({ length: Math.min(CONCURRENCY, todo.length) }, worker));
  const cost = (inputTokens * PRICE.input + outputTokens * PRICE.output) / 1_000_000;
  console.log(`\ndone: ${todo.length - failures.length} captioned, ${failures.length} failed; ${inputTokens} input + ${outputTokens} output tokens, about $${cost.toFixed(2)}`);
  for (const failure of failures) console.log(`  ${failure}`);
  if (failures.length) process.exitCode = 1;
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
